---
kubernetesVersion: v1.22.5+rke2r2
# none, calico, canal, cilium
cni: canal
kubevip:
  enabled: true
  controlplane: true
  controlplaneVip: 192.168.178.1
  interface: eth0
  services: true
  kubevipCloudProvider: true
