---
- name: PreFlight checks
  include: preFlightChecks.yaml

- name: Preinstall
  include: preInstall.yaml

- name: Install kubevip
  include: installKubevip.yaml
  when: clusterconfig.kubevip.enabled is true and hostvars[inventory_hostname]['ansible_facts']['default_ipv4']['address'] == hostvars[groups['servers'][0]]['ansible_default_ipv4']['address']

- name: Install server nodes
  include: installServer.yaml
  when: inventory_hostname in groups["servers"]

- name: Install agent nodes
  include: installAgent.yaml
  when: inventory_hostname in groups["agents"]
